### ISSUE TITLE
Use credentials plugin for publishing packages

### ISSUE THREAD

**Issue by phxql** [seu-as-code/seu-as-code.packages#26]
At the moment, the packages use project properties for nexusUrl, `nexusUsername` and `nexusPassword`. I think it would be great if we use the credentials plugin for the `nexusUsername` and `nexusPassword` properties.

**Comment by lreimer** [comment]
I understand your point, but I still think it is better this way.
- The package builds are meant as a blueprint usable by other people outside of QAware.
- Using the current credentials plugin would make the publishing process Windows dependent.
