### ISSUE TITLE
Add eclipse neon 32 bit package

### ISSUE THREAD

**Issue by andreaswe** [seu-as-code/seu-as-code.packages#41]
Add eclipse neon 32 bit package

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/41/559eb7c1-a8a9-4704-8942-7ea27cce007d/142a100b-9ac6-4562-9894-07257566ad88) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/41/559eb7c1-a8a9-4704-8942-7ea27cce007d/142a100b-9ac6-4562-9894-07257566ad88) for details.
