### ISSUE TITLE
Remove MaxPermSize from MAVEN_OPTS

### ISSUE THREAD

**Issue by andreaswe** [seu-as-code/seu-as-code.packages#43]
MAVEN_OPTS is set in set-env-apache-maven.cmd and set-env-apache-maven.sh with the option
`-XX:MaxPermSize=512M`

This option is not supported in JDK 8 anymore and should therefore be removed.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/43/559eb7c1-a8a9-4704-8942-7ea27cce007d/b36621d6-9e1a-4ffe-853c-2852a454bbb6) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/43/559eb7c1-a8a9-4704-8942-7ea27cce007d/b36621d6-9e1a-4ffe-853c-2852a454bbb6) for details.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/43/559eb7c1-a8a9-4704-8942-7ea27cce007d/b36621d6-9e1a-4ffe-853c-2852a454bbb6) for details.
