### ISSUE TITLE
Apply all environment variables in org.apache.db-derby

### ISSUE THREAD

**Issue by g3force** [seu-as-code/seu-as-code.packages#48]
The start-db-derby.sh script applies set-env-db-derby.sh instead of set-env.sh

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/48/559eb7c1-a8a9-4704-8942-7ea27cce007d/ba3a1987-a062-4079-95cb-962641e93c33) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/48/559eb7c1-a8a9-4704-8942-7ea27cce007d/ba3a1987-a062-4079-95cb-962641e93c33) for details.
