### ISSUE TITLE
Add Oracle JDK 1.8.0_144 package

### ISSUE THREAD

**Issue by fuchshuber** [seu-as-code/seu-as-code.packages#54]
New Oracle JDK 6 Update 144 is released. Download: http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-windows-x64.exe

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)
* Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/54/559eb7c1-a8a9-4704-8942-7ea27cce007d/0f7c8033-6f1f-4e46-a01d-e80532c32e77) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/54/559eb7c1-a8a9-4704-8942-7ea27cce007d/0f7c8033-6f1f-4e46-a01d-e80532c32e77) for details.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/54/559eb7c1-a8a9-4704-8942-7ea27cce007d/0f7c8033-6f1f-4e46-a01d-e80532c32e77) for details.

**Comment by lreimer** [comment]
Closed.
