### ISSUE TITLE
Add IntelliJ 2017.2.4 package

### ISSUE THREAD

**Issue by fuchshuber** [seu-as-code/seu-as-code.packages#55]
Windows version can be downloaded at https://download.jetbrains.com/idea/ideaIU-2017.2.4.win.zip

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/55/559eb7c1-a8a9-4704-8942-7ea27cce007d/f19af3d7-d69f-4a0a-96a8-4029d9c216ce) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by lreimer** [comment]
Pull Request?

**Comment by lreimer** [comment]
Outdated.
