### ISSUE TITLE
Add ElasticSearch 2.4.6 package

### ISSUE THREAD

**Issue by fuchshuber** [seu-as-code/seu-as-code.packages#56]
Download link: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.4.6.zip

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/56/559eb7c1-a8a9-4704-8942-7ea27cce007d/880e043d-a743-4389-8060-e9adea6fc5e3) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by lreimer** [comment]
Pull Request?

**Comment by lreimer** [comment]
Closed due to inactivity.
