### ISSUE TITLE
Bundled 7z for msysgit does not unpack git

### ISSUE THREAD

**Issue by ascheman** [seu-as-code/seu-as-code.packages#67]
The bundled 7z.exe in, e.g., `io.github.msysgit` is not able to unpack a downloaded zip archive. The gradle call aborts w/ 

```
Successfully started process 'command 'cmd''

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18


Error:
7-Zip cannot find the code that works with archives.
```

Probably the Windows dll is missing (cf. https://sourceforge.net/p/sevenzip/discussion/45797/thread/a01e0ce7/)?

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/67/559eb7c1-a8a9-4704-8942-7ea27cce007d/653ea7be-9943-4bd6-b07b-98b0d834ff5b) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/67/559eb7c1-a8a9-4704-8942-7ea27cce007d/653ea7be-9943-4bd6-b07b-98b0d834ff5b) for details.
