### ISSUE TITLE
gitmagic has bad configuration

### ISSUE THREAD

**Issue by ascheman** [seu-as-code/seu-as-code.packages#68]
After submitting a new bug report, gitmagic automatically adds some comments:

  https://github.com/seu-as-code/seu-as-code.packages/issues/67#issuecomment-368012485

However, for me (as a non member of the seu-as-code team?) it is not possible to provide a label. Please update your configuration.

I consider the other two guidelines also as wrong
* Issue titles might not always start with an uppercase letter, in particular when they refer to a well known term which starts with lowercase, e.g., _gitmagic_
* a bug report describes a bug, not necessarily some imperative order to the development team. One might even consider asking questions or starting a discussion to clarify something in an issue

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/68/559eb7c1-a8a9-4704-8942-7ea27cce007d/e1133008-f76f-4e5f-9916-192ae2b81b6a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/68/559eb7c1-a8a9-4704-8942-7ea27cce007d/e1133008-f76f-4e5f-9916-192ae2b81b6a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
