### ISSUE TITLE
Software hooks should run immediately after installation of each package

### ISSUE THREAD

**Issue by ascheman** [seu-as-code/seu-as-code.packages#69]
Software hooks seem to run after all outstanding packages are applied. If for some reason the installation of a package aborts (download failure or something else) the hooks are never executed and leave unpacked files with unresolved place holders.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/69/559eb7c1-a8a9-4704-8942-7ea27cce007d/70b16deb-8a3b-41e2-a35c-a9753c009a91) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by lreimer** [comment]
Closing issue here. Copied issue to seu-as-code/seu-as-code.plugins repo instead, since this behaviour is implemented in the base-plugin.
