### ISSUE TITLE
Add io.github.mysgit 2.16.2

### ISSUE THREAD

**Issue by ascheman** [seu-as-code/seu-as-code.packages#70]
Please add the latest Windows portable git version (2.16.2) as package

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/70/559eb7c1-a8a9-4704-8942-7ea27cce007d/1ac06a32-8fd3-4093-9a58-ae79c163865d) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
