### ISSUE TITLE
Clean CONTRIBUTING.md from puppetlabs etc.

### ISSUE THREAD

**Issue by ascheman** [seu-as-code/seu-as-code.packages#72]
The CONTRIBUTING guide talks about puppetlabs and a Jira issue tracker.
Is this a copy/paste issue?

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/72/559eb7c1-a8a9-4704-8942-7ea27cce007d/758b3e7a-cc89-48eb-8b40-873b96b367f1) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
