### ISSUE TITLE
Migrate remaining optional packages from internal repo

### ISSUE THREAD

**Issue by seu-as-code** [seu-as-code/seu-as-code.packages#9]
Do not migrate everything. No commercial tools.

**Comment by lreimer** [comment]
Pretty much migrated everything that is currently needed. Can be closed now.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.packages/9/559eb7c1-a8a9-4704-8942-7ea27cce007d/dd1ca07a-0a3b-4077-b365-9fe84b3aac1e) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
